Update make_repo_public.yml

diff --git a/.github/workflows/make_repo_public.yml b/.github/workflows/make_repo_public.yml
--- a/.github/workflows/make_repo_public.yml
+++ b/.github/workflows/make_repo_public.yml
@@ -41,11 +41,14 @@ jobs:
       - name: Disable workflow
         if: env.VISIBILITY_CHANGED == 'true'
         run: |
-          curl \
-            -X PUT \
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X PUT \
             -H "Authorization: token ${{ secrets.GH_PAT }}" \
             -H "Accept: application/vnd.github.v3+json" \
-            https://api.github.com/repos/${{ github.repository }}/actions/workflows/make_repo_public.yml/disable
+            https://api.github.com/repos/${{ github.repository }}/actions/workflows/make_repo_public.yml/disable)
+          if [ $RESPONSE -ne 204 ]; then
+            echo "Failed to disable workflow. HTTP response code: $RESPONSE"
+            exit 1
+          fi
       - name: Call webhook
         run: |
             RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" \
